local tagUsers = {}

tagUsers["Real_revvybxnned11"] = {
    ["Tag"] = "Founder",
    ["Color"] = Color3.fromRGB(239, 4, 255)
}

tagUsers["Poop79783"] = {
    ["Tag"] = "Scat Man",
    ["Color"] = Color3.fromRGB(116, 88, 255)
}

tagUsers["NicePoitUGC"] = {
    ["Tag"] = '"jew"',
    ["Color"] = Color3.fromRGB(150, 0, 0)
}

local cone = {
    ["Tag"] = "Cone",
    ["Color"] = Color3.fromRGB(255, 203, 92)
}
tagUsers["ConeVanilla_Furry"] = cone
tagUsers["CoderCoenFurri"] = cone
tagUsers["crctrev"] = cone
tagUsers["99luau"] = cone

return tagUsers
